export const MAP_CONSTANTS = {
  TILE_SIZE: 32,
  WIDTH: 80,
  HEIGHT: 60,
  NATIVE_SETTLEMENT_MIN_COUNT: 6,
  NATIVE_SETTLEMENT_MAX_COUNT: 10,
  NATIVE_SETTLEMENT_MIN_DISTANCE: 8,
  NATIVE_SETTLEMENT_EDGE_MARGIN: 8,
} as const;

export const UNIT_CONSTANTS = {
  DEFAULT_MOVES: 3,
  SHIP_MOVES: 6,
  PIONEER_MOVES: 3,
  SOLDIER_MOVES: 3,
  ANIMATION_DURATION: 200,
} as const;

export const COLONY_CONSTANTS = {
  INITIAL_POPULATION: 1,
  WAREHOUSE_CAPACITY: 400,
  DEFAULT_CAPACITY: 200,
  PRODUCTION_PER_WORKER: 3,
} as const;

export const BUILDING_COSTS = {
  LUMBER_MILL: 100,
  IRON_WORKS: 150,
  SCHOOLHOUSE: 120,
  WAREHOUSE: 80,
  STOCKADE: 200,
  PRINTING_PRESS: 180,
} as const;

export const RECRUITMENT_COSTS = {
  COLONIST: 500,
  SOLDIER: 800,
  PIONEER: 650,
} as const;
